[build]
publish = "_tmp/public"
command = "hack/generate-kcommunity-site.sh"

[context.production.environment]
HUGO_VERSION = "0.45.1"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
command = "hack/generate-kcommunity-site.sh --enableGitInfo -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
command = "hack/generate-kcommunity-site.sh --enableGitInfo -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.45.1"

[context.master]
publish = "_tmp/public"
command = "hack/generate-kcommunity-site.sh"