[build]
publish = "_tmp/public"
command = "hack/generate-kcommunity-site.sh"

[build.environment]
HUGO_VERSION = "0.45.1"

[context.production.environment]
HUGO_ENV = "production"

[context.deploy-preview]
command = "hack/generate-kcommunity-site.sh -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
command = "hack/generate-kcommunity-site.sh -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
command = "hack/generate-kcommunity-site.sh -b $DEPLOY_PRIME_URL"